### PR TITLE
update to COS 8.14.1 to pull in auth policy scope changes

### PR DESCRIPTION
**Pull request by ocofaigh**
### Description

update to COS 8.14.1 to pull in auth policy scope changes

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [x] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Comment by ocofaigh** [comment]
Need to wait for https://github.com/terraform-ibm-modules/terraform-ibm-cos/pull/765

**Comment by ocofaigh** [comment]
As expected, upgrade test failed with:
```
        	Messages:   	Resource(s) identified to be destroyed 
        	            	Name: policy
        	            	Address: module.cos[0].ibm_iam_authorization_policy.policy[0]
        	            	Actions: [create delete]
```

Since the code is going to do a create before destroy, there will be no disruption to services, so proceeding to skip upgrade test

**Review by daniel-butler-irl — APPROVED** [review]

**Pull request merged**
