### PR TITLE
fix: do not create auth policy if existing_cos_instance_crn is null

### PR DESCRIPTION
**Pull request by akocbek**
### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Comment by akocbek** [comment]
```Error: DeleteDestinationWithContext failed Unauthorized, service to service is not enabled
 2024/10/01 14:29:32 Terraform destroy | {
 2024/10/01 14:29:32 Terraform destroy |     "StatusCode": 401,
 2024/10/01 14:29:32 Terraform destroy |     "Headers": {
 2024/10/01 14:29:32 Terraform destroy |         "Access-Control-Allow-Credentials": [
 2024/10/01 14:29:32 Terraform destroy |             "true"
 2024/10/01 14:29:32 Terraform destroy |         ],
 2024/10/01 14:29:32 Terraform destroy |         "Access-Control-Allow-Headers": [
 2024/10/01 14:29:32 Terraform destroy |             "*"
 2024/10/01 14:29:32 Terraform destroy |         ],
 2024/10/01 14:29:32 Terraform destroy |         "Access-Control-Allow-Methods": [
 2024/10/01 14:29:32 Terraform destroy |             "POST, GET, OPTIONS, PUT, DELETE, PATCH"
 2024/10/01 14:29:32 Terraform destroy |         ],
 2024/10/01 14:29:32 Terraform destroy |         "Access-Control-Allow-Origin": [
 2024/10/01 14:29:32 Terraform destroy |             "*"
 2024/10/01 14:29:32 Terraform destroy |         ],
 2024/10/01 14:29:32 Terraform destroy |         "Cache-Control": [
 2024/10/01 14:29:32 Terraform destroy |             "No-Store"
 2024/10/01 14:29:32 Terraform destroy |         ],
 2024/10/01 14:29:32 Terraform destroy |         "Cf-Cache-Status": [
 2024/10/01 14:29:32 Terraform destroy |             "DYNAMIC"
 2024/10/01 14:29:32 Terraform destroy |         ],
 2024/10/01 14:29:32 Terraform destroy |         "Cf-Ray": [
 2024/10/01 14:29:32 Terraform destroy |             "8cbd24a9cc0e6b5b-DFW"
 2024/10/01 14:29:32 Terraform destroy |         ],
 2024/10/01 14:29:32 Terraform destroy |         "Content-Length": [
 2024/10/01 14:29:32 Terraform destroy |             "236"
 2024/10/01 14:29:32 Terraform destroy |         ],
 2024/10/01 14:29:32 Terraform destroy |         "Content-Security-Policy": [
 2024/10/01 14:29:32 Terraform destroy |             "script-src * 'unsafe-inline', frame-ancestors 'self'; form-action 'self'"
 2024/10/01 14:29:32 Terraform destroy |         ],
 2024/10/01 14:29:32 Terraform destroy |         "Content-Type": [
 2024/10/01 14:29:32 Terraform destroy |             "application/json"
 2024/10/01 14:29:32 Terraform destroy |         ],
 2024/10/01 14:29:32 Terraform destroy |         "Date": [
 2024/10/01 14:29:32 Terraform destroy |             "Tue, 01 Oct 2024 14:29:10 GMT"
 2024/10/01 14:29:32 Terraform destroy |         ],
 2024/10/01 14:29:32 Terraform destroy |         "Server": [
 2024/10/01 14:29:32 Terraform destroy |             "cloudflare"
 2024/10/01 14:29:32 Terraform destroy |         ],
 2024/10/01 14:29:32 Terraform destroy |         "Strict-Transport-Security": [
 2024/10/01 14:29:32 Terraform destroy |             "max-age=31536000; includeSubDomains"
 2024/10/01 14:29:32 Terraform destroy |         ],
 2024/10/01 14:29:32 Terraform destroy |         "X-Request-Id": [
 2024/10/01 14:29:32 Terraform destroy |             "46b03aa5-f539-4b0a-be70-33b3413338ae"
 2024/10/01 14:29:32 Terraform destroy |         ]
 2024/10/01 14:29:32 Terraform destroy |     },
 2024/10/01 14:29:32 Terraform destroy |     "Result": {
 2024/10/01 14:29:32 Terraform destroy |         "errors": [
 2024/10/01 14:29:32 Terraform destroy |             {
 2024/10/01 14:29:32 Terraform destroy |                 "code": "unauthorized_due_to_s2s",
 2024/10/01 14:29:32 Terraform destroy |                 "message": "Unauthorized, service to service is not enabled",
 2024/10/01 14:29:32 Terraform destroy |                 "more_info": "https://cloud.ibm.com/apidocs/event-notifications"
 2024/10/01 14:29:32 Terraform destroy |             }
 2024/10/01 14:29:32 Terraform destroy |         ],
 2024/10/01 14:29:32 Terraform destroy |         "status_code": 401,
 2024/10/01 14:29:32 Terraform destroy |         "trace": "ed80da8b-5a7f-46b4-9268-77c447728c2c"
 2024/10/01 14:29:32 Terraform destroy |     },
 2024/10/01 14:29:32 Terraform destroy |     "RawResult": null
 ```
 
 rerunning

**Comment by akocbek** [comment]
**before:** `TestRunExistingResourcesInstances` test failed when we added `ibmcloud_kms_api_key` with the following error and we reproduced the issue:

```
 on main.tf line 57, in resource "ibm_iam_authorization_policy" "cos_kms_policy":
 2024/10/01 15:03:37 Terraform plan |   57:   description                 = "Allow the COS instance with GUID ${local.cos_instance_guid} to read from the ${local.kms_service_name} instance GUID ${local.existing_kms_guid}"
 2024/10/01 15:03:37 Terraform plan |     ├────────────────
 2024/10/01 15:03:37 Terraform plan |     │ local.cos_instance_guid is null
 2024/10/01 15:03:37 Terraform plan | 
 2024/10/01 15:03:37 Terraform plan | The expression result is null. Cannot include a null value in a string
 2024/10/01 15:03:37 Terraform plan | template.
 2024/10/01 15:03:37 Terraform plan | 
 2024/10/01 15:03:37 Terraform plan | Error: Invalid index
 2024/10/01 15:03:37 Terraform plan | 
 2024/10/01 15:03:37 Terraform plan |   on main.tf line 66, in resource "ibm_iam_authorization_policy" "en_kms_policy":
 2024/10/01 15:03:37 Terraform plan |   66:   source_resource_instance_id = module.event_notifications[0].guid
 2024/10/01 15:03:37 Terraform plan |     ├────────────────
 2024/10/01 15:03:37 Terraform plan |     │ module.event_notifications is empty tuple
 2024/10/01 15:03:37 Terraform plan | 
 2024/10/01 15:03:37 Terraform plan | The given key does not identify an element in this collection value: the
 2024/10/01 15:03:37 Terraform plan | collection has no elements.
 2024/10/01 15:03:37 Terraform plan | 
 2024/10/01 15:03:37 Terraform plan | Error: Invalid index
 2024/10/01 15:03:37 Terraform plan | 
 2024/10/01 15:03:37 Terraform plan |   on main.tf line 70, in resource "ibm_iam_authorization_policy" "en_kms_policy":
 2024/10/01 15:03:37 Terraform plan |   70:   description                 = "Allow the EN instance with GUID ${module.event_notifications[0].guid} reader access to the ${local.kms_service_name} instance GUID ${local.existing_kms_guid}"
 2024/10/01 15:03:37 Terraform plan |     ├────────────────
 2024/10/01 15:03:37 Terraform plan |     │ module.event_notifications is empty tuple
 2024/10/01 15:03:37 Terraform plan | 
 2024/10/01 15:03:37 Terraform plan | The given key does not identify an element in this collection value: the
 2024/10/01 15:03:37 Terraform plan | collection has no elements.
 2024/10/01 15:03:37 [1m[31mTerraform PLAN error: Terraform PLAN errorexit status 1[39m[0m
 ```

**after:** `TestRunExistingResourcesInstances` pass with the proposed fix.

**Review by ocofaigh — APPROVED** [review]

**Pull request merged**
