### PR TITLE
feat: existing event notification instance support

### PR DESCRIPTION
**Pull request by iamar7**
### Description

Add support to pass existing event-notification instance.

Resolves: https://github.com/terraform-ibm-modules/terraform-ibm-event-notifications/issues/244

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [x] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Comment by Ak-sky** [comment]
Need to wait for this [PR](https://github.com/terraform-ibm-modules/terraform-ibm-event-notifications/pull/242) to get merged.

**Comment by ocofaigh** [comment]
@iamar7 pipeline is unblocked now if you want to get this one back ready

**Review by Aashiq-J — APPROVED** [review]
changes in-line with the scc-da [PR](https://github.com/terraform-ibm-modules/terraform-ibm-scc-da/pull/138/files) to add support for existing instance.

LGTM

**Pull request merged**
