### PR TITLE
feat: enabled COS bucket monitoring and activity tracking by default

### PR DESCRIPTION
**Pull request by ocofaigh**
### Description

enabled COS bucket monitoring and activity tracking by default for instances DA

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [x] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Comment by ocofaigh** [comment]
As expected, upgrade test failed as its trying to update the COS bucket to configure it with AT:
```
        	Messages:   	Resource(s) identified to be updated 
        	            	Name: cos_bucket
        	            	Address: module.cos[0].ibm_cos_bucket.cos_bucket[0]
        	            	Actions: [update]
        	            	DIFF:
        	            	  Before: 
        	            		{"activity_tracking":"SECURE_VALUE_HIDDEN_HASH:-2cf31ef4b9068796115faf1698203980238ee9d632aa95d6e707df47","metrics_monitoring":"SECURE_VALUE_HIDDEN_HASH:-2bfb8ec0bc256491a43981f46105bdc136d58b651b904a254220a028"}
        	            	  After: 
        	            		{"activity_tracking":"SECURE_VALUE_HIDDEN_HASH:-39fa5adb8e5eacf5cbd7b4a3dbb7ebda883316f65c32f40994c93f00","metrics_monitoring":"SECURE_VALUE_HIDDEN_HASH:-5541556ea85f571c29e44d521b08a38548f3b2ac0e55added9e67187"}
```

Its an update in place with no downtime to service, so skipping upgrade

**Comment by ocofaigh** [comment]
Destroy is failing for the `TestFSCloudInSchematics ` test with:
```
 2024/07/17 15:40:18 Terraform refresh | Error: ListIntegrationsWithContext failed Unfortunately you don't have a permission to access requested resource
 2024/07/17 15:40:18 Terraform refresh | {
 2024/07/17 15:40:18 Terraform refresh |     "StatusCode": 403,
 2024/07/17 15:40:18 Terraform refresh |     "Headers": {
 2024/07/17 15:40:18 Terraform refresh |         "Cf-Cache-Status": [
 2024/07/17 15:40:18 Terraform refresh |             "DYNAMIC"
 2024/07/17 15:40:18 Terraform refresh |         ],
 2024/07/17 15:40:18 Terraform refresh |         "Cf-Ray": [
 2024/07/17 15:40:18 Terraform refresh |             "8a4b54132ed96911-IAD"
 2024/07/17 15:40:18 Terraform refresh |         ],
 2024/07/17 15:40:18 Terraform refresh |         "Content-Type": [
 2024/07/17 15:40:18 Terraform refresh |             "application/json"
 2024/07/17 15:40:18 Terraform refresh |         ],
 2024/07/17 15:40:18 Terraform refresh |         "Date": [
 2024/07/17 15:40:18 Terraform refresh |             "Wed, 17 Jul 2024 15:40:05 GMT"
 2024/07/17 15:40:18 Terraform refresh |         ],
 2024/07/17 15:40:18 Terraform refresh |         "Server": [
 2024/07/17 15:40:18 Terraform refresh |             "cloudflare"
 2024/07/17 15:40:18 Terraform refresh |         ],
 2024/07/17 15:40:18 Terraform refresh |         "Strict-Transport-Security": [
 2024/07/17 15:40:18 Terraform refresh |             "max-age=31536000; includeSubDomains"
 2024/07/17 15:40:18 Terraform refresh |         ],
 2024/07/17 15:40:18 Terraform refresh |         "X-Envoy-Upstream-Service-Time": [
 2024/07/17 15:40:18 Terraform refresh |             "122"
 2024/07/17 15:40:18 Terraform refresh |         ],
 2024/07/17 15:40:18 Terraform refresh |         "X-Request-Id": [
 2024/07/17 15:40:18 Terraform refresh |             "ff871725-6d39-4221-9a81-ee52d59c5d20"
 2024/07/17 15:40:18 Terraform refresh |         ]
 2024/07/17 15:40:18 Terraform refresh |     },
 2024/07/17 15:40:18 Terraform refresh |     "Result": {
 2024/07/17 15:40:18 Terraform refresh |         "errors": [
 2024/07/17 15:40:18 Terraform refresh |             {
 2024/07/17 15:40:18 Terraform refresh |                 "code": "authorization_error",
 2024/07/17 15:40:18 Terraform refresh |                 "message": "Unfortunately you don't have a permission to access requested resource",
 2024/07/17 15:40:18 Terraform refresh |                 "more_info": "https://cloud.ibm.com/apidocs/event-notifications#event-notifications-api-authentication"
 2024/07/17 15:40:18 Terraform refresh |             }
 2024/07/17 15:40:18 Terraform refresh |         ],
 2024/07/17 15:40:18 Terraform refresh |         "status_code": 403,
 2024/07/17 15:40:18 Terraform refresh |         "trace": "54991394-772a-42ae-a33a-f7a745460486"
 2024/07/17 15:40:18 Terraform refresh |     },
 2024/07/17 15:40:18 Terraform refresh |     "RawResult": null
 2024/07/17 15:40:18 Terraform refresh | }
```

@Ak-sky Is it possible CBR is blocking this?

**Comment by Ak-sky** [comment]
> Destroy is failing for the `TestFSCloudInSchematics ` test with:
> 
> ```
>  2024/07/17 15:40:18 Terraform refresh | Error: ListIntegrationsWithContext failed Unfortunately you don't have a permission to access requested resource
>  2024/07/17 15:40:18 Terraform refresh | {
>  2024/07/17 15:40:18 Terraform refresh |     "StatusCode": 403,
>  2024/07/17 15:40:18 Terraform refresh |     "Headers": {
>  2024/07/17 15:40:18 Terraform refresh |         "Cf-Cache-Status": [
>  2024/07/17 15:40:18 Terraform refresh |             "DYNAMIC"
>  2024/07/17 15:40:18 Terraform refresh |         ],
>  2024/07/17 15:40:18 Terraform refresh |         "Cf-Ray": [
>  2024/07/17 15:40:18 Terraform refresh |             "8a4b54132ed96911-IAD"
>  2024/07/17 15:40:18 Terraform refresh |         ],
>  2024/07/17 15:40:18 Terraform refresh |         "Content-Type": [
>  2024/07/17 15:40:18 Terraform refresh |             "application/json"
>  2024/07/17 15:40:18 Terraform refresh |         ],
>  2024/07/17 15:40:18 Terraform refresh |         "Date": [
>  2024/07/17 15:40:18 Terraform refresh |             "Wed, 17 Jul 2024 15:40:05 GMT"
>  2024/07/17 15:40:18 Terraform refresh |         ],
>  2024/07/17 15:40:18 Terraform refresh |         "Server": [
>  2024/07/17 15:40:18 Terraform refresh |             "cloudflare"
>  2024/07/17 15:40:18 Terraform refresh |         ],
>  2024/07/17 15:40:18 Terraform refresh |         "Strict-Transport-Security": [
>  2024/07/17 15:40:18 Terraform refresh |             "max-age=31536000; includeSubDomains"
>  2024/07/17 15:40:18 Terraform refresh |         ],
>  2024/07/17 15:40:18 Terraform refresh |         "X-Envoy-Upstream-Service-Time": [
>  2024/07/17 15:40:18 Terraform refresh |             "122"
>  2024/07/17 15:40:18 Terraform refresh |         ],
>  2024/07/17 15:40:18 Terraform refresh |         "X-Request-Id": [
>  2024/07/17 15:40:18 Terraform refresh |             "ff871725-6d39-4221-9a81-ee52d59c5d20"
>  2024/07/17 15:40:18 Terraform refresh |         ]
>  2024/07/17 15:40:18 Terraform refresh |     },
>  2024/07/17 15:40:18 Terraform refresh |     "Result": {
>  2024/07/17 15:40:18 Terraform refresh |         "errors": [
>  2024/07/17 15:40:18 Terraform refresh |             {
>  2024/07/17 15:40:18 Terraform refresh |                 "code": "authorization_error",
>  2024/07/17 15:40:18 Terraform refresh |                 "message": "Unfortunately you don't have a permission to access requested resource",
>  2024/07/17 15:40:18 Terraform refresh |                 "more_info": "https://cloud.ibm.com/apidocs/event-notifications#event-notifications-api-authentication"
>  2024/07/17 15:40:18 Terraform refresh |             }
>  2024/07/17 15:40:18 Terraform refresh |         ],
>  2024/07/17 15:40:18 Terraform refresh |         "status_code": 403,
>  2024/07/17 15:40:18 Terraform refresh |         "trace": "54991394-772a-42ae-a33a-f7a745460486"
>  2024/07/17 15:40:18 Terraform refresh |     },
>  2024/07/17 15:40:18 Terraform refresh |     "RawResult": null
>  2024/07/17 15:40:18 Terraform refresh | }
> ```
> 
> @Ak-sky Is it possible CBR is blocking this?

Yes, it is happening for every PR run, I am not sure how it passed in this [PR](https://github.com/terraform-ibm-modules/terraform-ibm-event-notifications/pull/251). When ppdating [this](https://github.com/terraform-ibm-modules/terraform-ibm-event-notifications/blob/50d21dbf030f946503c17b051348614f4ecdb20c/examples/fscloud/main.tf#L151) endpoint from private to public for schematics, it is running successfully.

**Review by Ak-sky — APPROVED** [review]

**Comment by Ak-sky** [comment]
PR test failed due to` Provider produced inconsistent result after apply`


> Creation complete after 30s [id=2024-07-24T05:12:22Z]
>  2024/07/24 05:12:22 Terraform apply | module.event_notification.ibm_en_integration_cos.en_cos_integration[0]: Creating...
>  2024/07/24 05:12:22 Terraform apply | module.event_notification.ibm_en_integration.en_kms_integration[0]: Creation complete after 2s [id=dc46343f-9861-4ab0-a75c-347700d177ba/622e08c4-eb28-404d-8c2a-cc318e0466cf]
>  2024/07/24 05:12:23 Terraform apply | module.event_notification.ibm_en_integration_cos.en_cos_integration[0]: Creation complete after 2s [id=dc46343f-9861-4ab0-a75c-347700d177ba/b483d50c-f84a-4945-aab7-db008b984866]
>  2024/07/24 05:12:31 Terraform apply | ibm_is_subnet.testacc_subnet: Still creating... [10s elapsed]
>  2024/07/24 05:12:41 Terraform apply | ibm_is_subnet.testacc_subnet: Still creating... [20s elapsed]
>  2024/07/24 05:12:51 Terraform apply | ibm_is_subnet.testacc_subnet: Still creating... [30s elapsed]
>  2024/07/24 05:13:01 Terraform apply | ibm_is_subnet.testacc_subnet: Still creating... [40s elapsed]
>  2024/07/24 05:13:08 Terraform apply | ibm_is_subnet.testacc_subnet: Creation complete after 47s [id=02w7-1b5ecfab-253b-492a-bc48-1652a6aa9cc6]
>  2024/07/24 05:13:08 Terraform apply | 
>  2024/07/24 05:13:08 Terraform apply | Error: Provider produced inconsistent result after apply
>  2024/07/24 05:13:08 Terraform apply | 
>  2024/07/24 05:13:08 Terraform apply | When applying changes to module.cbr_vpc_zone.ibm_cbr_zone.cbr_zone, provider
>  2024/07/24 05:13:08 Terraform apply | "provider[\"registry.terraform.io/ibm-cloud/ibm\"]" produced an unexpected
>  2024/07/24 05:13:08 Terraform apply | new value: Root object was present, but now absent.
>  2024/07/24 05:13:08 Terraform apply | 
>  2024/07/24 05:13:08 Terraform apply | This is a bug in the provider, which should be reported in the provider's own
>  2024/07/24 05:13:08 Terraform apply | issue tracker.
>  2024/07/24 05:13:08 [1m[31mTerraform APPLY error: Terraform APPLY errorexit status 1[39m[0m
>  2024/07/24 05:13:08 [1m[31mCould not execute job: Error : Terraform APPLY errorexit status 1[39m[0m

**Pull request merged**
