### PR TITLE
fix: updated cbr enforcement mode

### PR DESCRIPTION
**Pull request by Ak-sky**
### Description

Update the CBR enforcement mode to enabled as the report is not supported. This is newly introduced SMTP API  in EN that does not support monitoring.
[Git Issue](https://github.com/terraform-ibm-modules/terraform-ibm-event-notifications/issues/250)

### Release required?

- [ ] No release
- [x] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Comment by Ak-sky** [comment]
PR test is keep on failing due to some issue in Schematics-

```
 2024/07/14 15:27:58 Terraform init | Downloading registry.terraform.io/terraform-ibm-modules/resource-group/ibm 1.1.6 for resource_group...
 2024/07/14 15:28:01 Terraform init | - resource_group in .terraform/modules/resource_group
 2024/07/14 15:28:01 Terraform init | 
 2024/07/14 15:28:01 Terraform init | Error: Unreadable module directory
 2024/07/14 15:28:01 Terraform init | 
 2024/07/14 15:28:01 Terraform init | Unable to evaluate directory symlink: lstat ../../modules: no such file or
 2024/07/14 15:28:01 Terraform init | directory
 2024/07/14 15:28:01 Terraform init | 
 2024/07/14 15:28:01 Terraform init | 
 2024/07/14 15:28:01 Terraform init | Error: Unreadable module directory
 2024/07/14 15:28:01 Terraform init | 
 2024/07/14 15:28:01 Terraform init | The directory  could not be read for module "event_notification" at
 2024/07/14 15:28:01 Terraform init | main.tf:89.
 2024/07/14 15:28:01 Terraform init | 
 2024/07/14 15:28:01 [1m[31mTerraform INIT error: Terraform INIT errorexit status 1[39m[0m
 2024/07/14 15:28:01 [1m[31mCould not execute job: Error : Terraform INIT errorexit status 1[39m[0m
```

**Review by ocofaigh — APPROVED** [review]

**Pull request merged**
