### PR TITLE
fix(deps): update terraform terraform-ibm-modules/cos/ibm to v8.6.2

### PR DESCRIPTION
**Pull request by Aashiq-J**
### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [x] Major release (`X.x.x`)

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Comment by Aashiq-J** [comment]
Expected upgrade test failure.
```
=== NAME  TestRunUpgradeDASolution
    tests.go:189: 
        	Error Trace:	/go/pkg/mod/github.com/terraform-ibm-modules/ibmcloud-terratest-wrapper@v1.35.2/testhelper/tests.go:189
        	            				/go/pkg/mod/github.com/terraform-ibm-modules/ibmcloud-terratest-wrapper@v1.35.2/testhelper/tests.go:764
        	            				/__w/terraform-ibm-event-notifications/terraform-ibm-event-notifications/tests/pr_test.go:149
        	Error:      	Should be false
        	Test:       	TestRunUpgradeDASolution
        	Messages:   	Resource(s) identified to be updated 
        	            	Name: cos_bucket
        	            	Address: module.cos[0].ibm_cos_bucket.cos_bucket[0]
        	            	Actions: [update]
        	            	DIFF:
        	            	  Before: 
        	            		{"activity_tracking":"SECURE_VALUE_HIDDEN_HASH:-40810d21e624676261396315be780d13df0481befe81bf2b41a88feb","metrics_monitoring":"SECURE_VALUE_HIDDEN_HASH:-c51466d72de0c88099c918d5a372b341423766a2d95c232de8be148e"}
        	            	  After: 
        	            		{"activity_tracking":"SECURE_VALUE_HIDDEN_HASH:-6baf0a3df2857411dc275ccb716241f170929962b24e2bf05ea94923","metrics_monitoring":"SECURE_VALUE_HIDDEN_HASH:-0878678d869aeb3564773c0e340a9b5399d07b3a816da3a03606b83a"}
```

This is due to the major version change to the [cos module](https://github.com/terraform-ibm-modules/terraform-ibm-cos/releases/tag/v8.6.0).

Skipping upgrade test

**Comment by Aashiq-J** [comment]
SKIP UPGRADE TEST

**Comment by Ak-sky** [comment]
Currently blocked by https://github.com/terraform-ibm-modules/terraform-ibm-event-notifications/pull/251

**Review by Ak-sky — DISMISSED** [review]

**Comment by Ak-sky** [comment]
Need to wait for this [PR](https://github.com/terraform-ibm-modules/terraform-ibm-event-notifications/pull/242) to get merged.

**Comment by Aashiq-J** [comment]
cos version already updated in this [PR](https://github.com/terraform-ibm-modules/terraform-ibm-event-notifications/pull/255).

Closing this

**Pull request closed without merging**
