### PR TITLE
fix: updated the default COS instance name that is used by the DA

### PR DESCRIPTION
**Pull request by ocofaigh**
### Description

fix for https://github.com/terraform-ibm-modules/dev-rag/issues/40

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Comment by ocofaigh** [comment]
Upgrade test failed (as expected) with this update:
```
        	Messages:   	Resource(s) identified to be updated 
        	            	Name: cos_instance
        	            	Address: module.cos[0].ibm_resource_instance.cos_instance[0]
        	            	Actions: [update]
        	            	DIFF:
        	            	  Before: 
        	            		{"name":"base-security-services-cos"}
        	            	  After: 
        	            		{"name":"base-event-notifications-cos"}
```

No impact to the service itself, so fine to skip test

**Review by akocbek — APPROVED** [review]

**Comment by ocofaigh** [comment]
Issues creating CBRs:
```
2024/09/12 16:18:31 Terraform apply | Error: context deadline exceeded
 2024/09/12 16:18:31 Terraform apply | 
 2024/09/12 16:18:31 Terraform apply |   with module.cbr_vpc_zone.ibm_cbr_zone.cbr_zone,
 2024/09/12 16:18:31 Terraform apply |   on .terraform/modules/cbr_vpc_zone/modules/cbr-zone-module/main.tf line 7, in resource "ibm_cbr_zone" "cbr_zone":
 2024/09/12 16:18:31 Terraform apply |    7: resource "ibm_cbr_zone" "cbr_zone" {
 2024/09/12 16:18:31 Terraform apply | 
 2024/09/12 16:18:31 Terraform apply | 
 2024/09/12 16:18:31 Terraform apply | Error: context deadline exceeded
 2024/09/12 16:18:31 Terraform apply | 
 2024/09/12 16:18:31 Terraform apply |   with module.cbr_zone_schematics.ibm_cbr_zone.cbr_zone,
 2024/09/12 16:18:31 Terraform apply |   on .terraform/modules/cbr_zone_schematics/modules/cbr-zone-module/main.tf line 7, in resource "ibm_cbr_zone" "cbr_zone":
 2024/09/12 16:18:31 Terraform apply |    7: resource "ibm_cbr_zone" "cbr_zone" {
```

Unrelated to code in this PR, so re-running..

**Pull request merged**
